AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AI Resume Editor - Serverless Pipeline using Bedrock, Lambda and Step Functions.

Parameters:
  GitHubToken:
    Type: String
    Description: GitHub Personal Access Token
    NoEcho: true
  GitHubRepo:
    Type: String
    Description: Repository name (e.g., username/repo)
    Default: Vishhh03/Latex-Resume # Update this default or pass in deploy

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Handler: handlers.lambda_handler
    Runtime: python3.9
    Environment:
      Variables:
        GITHUB_TOKEN: !Ref GitHubToken
        GITHUB_REPO: !Ref GitHubRepo

Resources:
  # --- API Gateway ---
  ResumeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  # --- Step Function ---
  ResumeStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/resume_workflow.asl.json
      DefinitionSubstitutions:
        FetchResumeFunctionArn: !GetAtt FetchResumeFunction.Arn
        GenerateDiffFunctionArn: !GetAtt GenerateDiffFunction.Arn
        CommitUpdateFunctionArn: !GetAtt CommitUpdateFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref FetchResumeFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateDiffFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CommitUpdateFunction
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            RestApiId: !Ref ResumeApi
            Path: /update
            Method: POST

  # --- Lambda Functions ---
  FetchResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_src/
      Handler: handlers.fetch_resume
      Policies:
        - Statement:
            - Effect: Allow
              Action: [ "ssm:GetParameter" ] 
              Resource: "*" # Scope down in prod

  GenerateDiffFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_src/
      Handler: handlers.generate_diff
      Policies:
        - Statement:
            - Effect: Allow
              Action: [ "bedrock:InvokeModel" ]
              Resource: "*" # Scope down to specific model ARN if needed
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationsTable

  CommitUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_src/
      Handler: handlers.commit_update
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationsTable
      Environment:
        Variables:
          GITHUB_TOKEN: !Ref GitHubToken
          GITHUB_REPO: !Ref GitHubRepo

  GetHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_src/
      Handler: handlers.get_history_handler
      Environment:
        Variables:
          GITHUB_TOKEN: !Ref GitHubToken
          GITHUB_REPO: !Ref GitHubRepo
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            RestApiId: !Ref ResumeApi
            Path: /history
            Method: GET

  GetResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_src/
      Handler: handlers.get_resume_handler
      Environment:
        Variables:
          GITHUB_TOKEN: !Ref GitHubToken
          GITHUB_REPO: !Ref GitHubRepo
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            RestApiId: !Ref ResumeApi
            Path: /resume
            Method: GET

  SaveResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_src/
      Handler: handlers.save_resume_handler
      Environment:
        Variables:
          GITHUB_TOKEN: !Ref GitHubToken
          GITHUB_REPO: !Ref GitHubRepo
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            RestApiId: !Ref ResumeApi
            Path: /save
            Method: POST

  ConversationsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: conversation_id
        Type: String

  PdfBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "resume-previews-${AWS::AccountId}-${AWS::Region}"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: ["GET"]
            AllowedOrigins: ["*"]

  CompilePdfFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 2048
      Timeout: 60
      Environment:
        Variables:
          PDF_BUCKET: !Ref PdfBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PdfBucket
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            RestApiId: !Ref ResumeApi
            Path: /preview
            Method: POST
    Metadata:
      DockerTag: python3.9-v1
      DockerContext: lambda_src/compile_pdf
      Dockerfile: Dockerfile

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ResumeApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update"
  PreviewBucket:
    Description: "S3 Bucket for PDF previews"
    Value: !Ref PdfBucket
